[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
{{project-name}}-common = { path = "../{{project-name}}-common", features = ["user"] }
{% if program_types_with_opts contains program_type -%}
clap = { version = "4.1", features = ["derive"] }
{% endif -%}
aya = { version = ">=0.11", features = ["async_tokio"] }
aya-log = "0.1"
anyhow = "1.0.42"
env_logger = "0.10"
libc = "0.2"
log = "0.4"
tokio = { version = "1.23", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
] }

[[bin]]
name = "{{project-name}}"
path = "src/main.rs"
